name = "SmithThesisRegistry"
uuid = "36792399-b749-4824-8e0a-635f2d19cb0c"
repo = "https://github.com/grahamas/SmithThesisRegistry.git"
description = "Registry of packages for Graham Smith's PhD thesis and related papers"

[packages]
310cc8c8-1ffe-11e9-399c-c5a008d6bdcc = { name = "Simulation73", path = "S/Simulation73" }
a199b2c4-7a51-11e9-2fe1-b9a1a5fe2912 = { name = "NeuralModels", path = "N/NeuralModels" }
