name = "SmithThesisRegistry"
uuid = "36792399-b749-4824-8e0a-635f2d19cb0c"
repo = "https://github.com/grahamas/SmithThesisRegistry.git"
description = "Registry of packages for Graham Smith's PhD thesis and related papers"

[packages]
090ce58c-883b-45c9-8a81-7f2bda835033 = { name = "TravelingWaveSimulationsPlotting", path = "T/TravelingWaveSimulationsPlotting" }
2846d769-be22-4083-a76c-fdabc4869842 = { name = "Simulation73Plotting", path = "S/Simulation73Plotting" }
310cc8c8-1ffe-11e9-399c-c5a008d6bdcc = { name = "Simulation73", path = "S/Simulation73" }
6a41bcfa-3301-11ec-2a0d-df01ea421e5a = { name = "TripleCorrelations", path = "T/TripleCorrelations" }
72e6b469-206c-443f-8d03-b2dd71534e00 = { name = "NamedDimsHelpers", path = "N/NamedDimsHelpers" }
8b008879-e0cd-496b-b569-b901d37ab395 = { name = "TriCorrApplications", path = "T/TriCorrApplications" }
a199b2c4-7a51-11e9-2fe1-b9a1a5fe2912 = { name = "NeuralModels", path = "N/NeuralModels" }
b032b04e-6398-4201-8d15-161497fcf6c6 = { name = "NullclineAnalysis", path = "N/NullclineAnalysis" }
b7a787de-74f3-11e9-2c3d-21bc6dc7d0e1 = { name = "TravelingWaveSimulations", path = "T/TravelingWaveSimulations" }
bdbc91b4-201b-11e9-2b98-89611552dcef = { name = "WilsonCowanModel", path = "W/WilsonCowanModel" }
